### ISSUE TITLE
MenuScene으로 전환할때 circular import 오류

### ISSUE THREAD

**Issue by Seeyou2000** [Seeyou2000/SE_UNO_Project#2]
187276c532e68de1dcb199317109241e8ada80dc

https://github.com/Seeyou2000/SE_UNO_Project/commit/187276c532e68de1dcb199317109241e8ada80dc#diff-63313568182a0d910bad194bedd4a131d461ba7cb65791895d58ff0873dc344cR21-R22

**Comment by gidongkwon** [comment]
#4
