### ISSUE TITLE
뒤로가기 버튼의 위치가 일관적이지 않은 문제

### ISSUE THREAD

**Issue by gidongkwon** [Seeyou2000/SE_UNO_Project#30]
뒤로가기 버튼이 화면마다 다른곳에 있어서 아주 헷갈립니다. 모든 화면에서 통일된 위치를 가져가면 좋겠습니다.

**Comment by Seeyou2000** [comment]
뒤로가기 버튼을 왼쪽 위로 하자고 했는데, 설정 버튼도 왼쪽 위로 옮길까요?

**Comment by gidongkwon** [comment]
ㄱㄱㄱ
